from . import account_tax
from . import product_product
from . import product_category
from . import product_template
from . import res_company
from . import res_partner
from . import res_config
from . import res_users
from . import product_pricelist