{
    "id": 145,
    "price": 0.0,
    "price_extra": 0.0,
    "lst_price": 1.0,
    "default_code": "123asd",
    "code": "123asd",
    "partner_ref": "[123asd] Envase aceite",
    "active": True,
    "product_tmpl_id": (76, "[123asd] Envase aceite"),
    "barcode": False,
    "product_template_attribute_value_ids": [],
    "combination_indices": "",
    "is_product_variant": True,
    "standard_price": 0.0,
    "volume": 0.0,
    "weight": 0.0,
    "pricelist_item_count": 0,
    "packaging_ids": [],
    "image_variant_1920": False,
    "image_variant_1024": False,
    "image_variant_512": False,
    "image_variant_256": False,
    "image_variant_128": False,
    "can_image_variant_1024_be_zoomed": False,
    "image_1920": False,
    "image_1024": False,
    "image_512": False,
    "image_256": False,
    "image_128": False,
    "can_image_1024_be_zoomed": False,
    "stock_quant_ids": [],
    "stock_move_ids": [],
    "qty_available": 0.0,
    "virtual_available": 0.0,
    "free_qty": 0.0,
    "incoming_qty": 0.0,
    "outgoing_qty": 0.0,
    "orderpoint_ids": [],
    "nbr_reordering_rules": 0,
    "reordering_min_qty": 0.0,
    "reordering_max_qty": 0.0,
    "putaway_rule_ids": [],
    "variant_bom_ids": [],
    "bom_line_ids": [],
    "bom_count": 0,
    "used_in_bom_count": 0,
    "mrp_product_qty": 0.0,
    "activity_ids": [],
    "activity_state": False,
    "activity_date_deadline": False,
    "activity_exception_decoration": False,
    "activity_exception_icon": False,
    "message_is_follower": True,
    "message_follower_ids": [1256],
    "message_partner_ids": [3],
    "message_channel_ids": [],
    "message_ids": [1701],
    "message_unread": False,
    "message_unread_counter": 0,
    "message_needaction": False,
    "message_needaction_counter": 0,
    "message_has_error": False,
    "message_has_error_counter": 0,
    "message_attachment_count": 0,
    "message_main_attachment_id": False,
    "website_message_ids": [],
    "message_has_sms_error": False,
    "purchased_product_qty": 0.0,
    "value_svl": 0.0,
    "quantity_svl": 0.0,
    "stock_valuation_layer_ids": [],
    "sales_count": 0.0,
    "website_id": False,
    "product_variant_image_ids": [],
    "website_url": "/shop/product/123asd-envase-aceite-76#attr=",
    "cart_qty": 0,
    "activity_user_id": False,
    "activity_type_id": False,
    "activity_summary": False,
    "display_name": "[123asd] Envase aceite",
    "create_uid": (2, "Mitchell Admin DEBO"),
    "create_date": datetime.datetime(2021, 8, 6, 19, 6, 4, 516208),
    "write_uid": (2, "Mitchell Admin DEBO"),
    "write_date": datetime.datetime(2021, 8, 6, 19, 9, 6, 429076),
    "__last_update": datetime.datetime(2021, 8, 6, 19, 9, 6, 429076),
    "name": "Envase aceite",
    "sequence": 1,
    "description": False,
    "description_purchase": False,
    "description_sale": False,
    "rental": False,
    "categ_id": (1, "All"),
    "currency_id": (19, "ARS"),
    "cost_currency_id": (19, "ARS"),
    "list_price": 1.0,
    "volume_uom_name": "m³",
    "weight_uom_name": "kg",
    "sale_ok": True,
    "purchase_ok": True,
    "pricelist_id": False,
    "uom_id": (11, "Litros"),
    "uom_name": "Litros",
    "uom_po_id": (11, "Litros"),
    "company_id": False,
    "seller_ids": [],
    "variant_seller_ids": [],
    "color": 0,
    "attribute_line_ids": [],
    "valid_product_template_attribute_line_ids": [],
    "product_variant_ids": [145],
    "product_variant_id": (145, "[123asd] Envase aceite"),
    "product_variant_count": 1,
    "has_configurable_attributes": False,
    "uom_category_id": (5, "Volumen"),
    "uom_ids": [3, 4, 5],
    "responsible_id": (2, "Mitchell Admin DEBO"),
    "type": "product",
    "property_stock_production": (
        41,
        "Virtual Locations/(AR) Responsable Inscripto: Production",
    ),
    "property_stock_inventory": (
        37,
        "Virtual Locations/(AR) Responsable Inscripto: Inventory adjustment",
    ),
    "sale_delay": 0.0,
    "tracking": "none",
    "description_picking": False,
    "description_pickingout": False,
    "description_pickingin": False,
    "location_id": False,
    "warehouse_id": False,
    "route_from_categ_ids": [],
    "bom_ids": [],
    "produce_delay": 0.0,
    "life_time": 0,
    "use_time": 0,
    "removal_time": 0,
    "alert_time": 0,
    "taxes_id": [137],
    "supplier_taxes_id": [138],
    "property_account_income_id": False,
    "property_account_expense_id": False,
    "rating_ids": [],
    "rating_last_value": 0.0,
    "rating_count": 0,
    "rating_avg": 0.0,
    "is_seo_optimized": False,
    "website_meta_title": False,
    "website_meta_description": False,
    "website_meta_keywords": False,
    "website_meta_og_img": False,
    "website_published": False,
    "is_published": False,
    "can_publish": True,
    "rating_last_feedback": False,
    "rating_last_image": False,
    "property_account_creditor_price_difference": False,
    "purchase_method": "receive",
    "purchase_line_warn": "no-message",
    "purchase_line_warn_msg": False,
    "cost_method": "standard",
    "valuation": "manual_periodic",
    "available_in_pos": False,
    "to_weight": False,
    "pos_categ_id": False,
    "purchase_requisition": "rfq",
    "route_ids": [27],
    "service_type": "manual",
    "sale_line_warn": "no-message",
    "sale_line_warn_msg": False,
    "expense_policy": "no",
    "visible_expense_policy": True,
    "visible_qty_configurator": True,
    "invoice_policy": "order",
    "optional_product_ids": [],
    "service_to_purchase": False,
    "website_description": False,
    "alternative_product_ids": [],
    "accessory_product_ids": [],
    "website_size_x": 1,
    "website_size_y": 1,
    "website_style_ids": [],
    "website_sequence": 10065,
    "public_categ_ids": [],
    "product_template_image_ids": [],
    "product_add_mode": "configurator",
    "quotation_only_description": False,
    "quotation_description": "",
    "inventory_availability": "never",
    "available_threshold": 0.0,
    "custom_message": "",
    "arba_code": False,
}

#TAXES
{
    "id": 137,
    "name": "IVA 21%",
    "active": True,
    "company_id": (4, "(AR) Responsable Inscripto"),
    "children_tax_ids": [],
    "sequence": 1,
    "description": "IVA 21%",
    "price_include": True,
    "include_base_amount": False,
    "analytic": False,
    "tax_group_id": (2, "IVA 21%"),
    "hide_tax_exigibility": False,
    "tax_exigibility": "on_invoice",
    "cash_basis_transition_account_id": False,
    "cash_basis_base_account_id": False,
    "invoice_repartition_line_ids": [525, 526],
    "refund_repartition_line_ids": [565, 566],
    "country_id": (10, "Argentina"),
    "type_tax_use": "sale",
    "amount": 21.0,
    "withholding_sequence_id": False,
    "withholding_non_taxable_amount": 0.0,
    "withholding_non_taxable_minimum": 0.0,
    "withholding_amount_type": False,
    "withholding_user_error_message": False,
    "withholding_user_error_domain": "[]",
    "withholding_advances": True,
    "withholding_accumulated_payments": False,
    "withholding_python_compute": "\n# withholdable_base_amount\n# payment: account.payment.group object\n# partner: res.partner object (commercial partner of payment group)\n# withholding_tax: account.tax.withholding object\n\nresult = withholdable_base_amount * 0.10\n        ",
    "withholding_rule_ids": [],
    "jurisdiction_code": False,
    "amount_type": "percent",
    "withholding_type": "none",
    "display_name": "IVA 21%",
    "create_uid": (1, "OdooBot"),
    "create_date": datetime.datetime(2021, 6, 14, 21, 11, 9, 26427),
    "write_uid": (13, "Diego Maylin"),
    "write_date": datetime.datetime(2021, 8, 9, 19, 22, 39, 347776),
    "__last_update": datetime.datetime(2021, 8, 9, 19, 22, 39, 347776),
}
