# PRODUCT
{
    "id": 145,
    "price": 0.0,
    "price_extra": 0.0,
    "lst_price": 1.0,
    "default_code": "123asd",
    "code": "123asd",
    "partner_ref": "[123asd] Envase aceite",
    "active": True,
    "product_tmpl_id": (76, "[123asd] Envase aceite"),
    "barcode": False,
    "product_template_attribute_value_ids": [],
    "combination_indices": "",
    "is_product_variant": True,
    "standard_price": 0.0,
    "volume": 0.0,
    "weight": 0.0,
    "pricelist_item_count": 0,
    "packaging_ids": [],
    "image_variant_1920": False,
    "image_variant_1024": False,
    "image_variant_512": False,
    "image_variant_256": False,
    "image_variant_128": False,
    "can_image_variant_1024_be_zoomed": False,
    "image_1920": False,
    "image_1024": False,
    "image_512": False,
    "image_256": False,
    "image_128": False,
    "can_image_1024_be_zoomed": False,
    "stock_quant_ids": [],
    "stock_move_ids": [],
    "qty_available": 0.0,
    "virtual_available": 0.0,
    "free_qty": 0.0,
    "incoming_qty": 0.0,
    "outgoing_qty": 0.0,
    "orderpoint_ids": [],
    "nbr_reordering_rules": 0,
    "reordering_min_qty": 0.0,
    "reordering_max_qty": 0.0,
    "putaway_rule_ids": [],
    "variant_bom_ids": [],
    "bom_line_ids": [],
    "bom_count": 0,
    "used_in_bom_count": 0,
    "mrp_product_qty": 0.0,
    "activity_ids": [],
    "activity_state": False,
    "activity_date_deadline": False,
    "activity_exception_decoration": False,
    "activity_exception_icon": False,
    "message_is_follower": True,
    "message_follower_ids": [1256],
    "message_partner_ids": [3],
    "message_channel_ids": [],
    "message_ids": [1701],
    "message_unread": False,
    "message_unread_counter": 0,
    "message_needaction": False,
    "message_needaction_counter": 0,
    "message_has_error": False,
    "message_has_error_counter": 0,
    "message_attachment_count": 0,
    "message_main_attachment_id": False,
    "website_message_ids": [],
    "message_has_sms_error": False,
    "purchased_product_qty": 0.0,
    "value_svl": 0.0,
    "quantity_svl": 0.0,
    "stock_valuation_layer_ids": [],
    "sales_count": 0.0,
    "website_id": False,
    "product_variant_image_ids": [],
    "website_url": "/shop/product/123asd-envase-aceite-76#attr=",
    "cart_qty": 0,
    "activity_user_id": False,
    "activity_type_id": False,
    "activity_summary": False,
    "display_name": "[123asd] Envase aceite",
    "create_uid": (2, "Mitchell Admin DEBO"),
    "create_date": datetime.datetime(2021, 8, 6, 19, 6, 4, 516208),
    "write_uid": (2, "Mitchell Admin DEBO"),
    "write_date": datetime.datetime(2021, 8, 6, 19, 9, 6, 429076),
    "__last_update": datetime.datetime(2021, 8, 6, 19, 9, 6, 429076),
    "name": "Envase aceite",
    "sequence": 1,
    "description": False,
    "description_purchase": False,
    "description_sale": False,
    "rental": False,
    "categ_id": (1, "All"),
    "currency_id": (19, "ARS"),
    "cost_currency_id": (19, "ARS"),
    "list_price": 1.0,
    "volume_uom_name": "m³",
    "weight_uom_name": "kg",
    "sale_ok": True,
    "purchase_ok": True,
    "pricelist_id": False,
    "uom_id": (11, "Litros"),
    "uom_name": "Litros",
    "uom_po_id": (11, "Litros"),
    "company_id": False,
    "seller_ids": [],
    "variant_seller_ids": [],
    "color": 0,
    "attribute_line_ids": [],
    "valid_product_template_attribute_line_ids": [],
    "product_variant_ids": [145],
    "product_variant_id": (145, "[123asd] Envase aceite"),
    "product_variant_count": 1,
    "has_configurable_attributes": False,
    "uom_category_id": (5, "Volumen"),
    "uom_ids": [3, 4, 5],
    "responsible_id": (2, "Mitchell Admin DEBO"),
    "type": "product",
    "property_stock_production": (
        41,
        "Virtual Locations/(AR) Responsable Inscripto: Production",
    ),
    "property_stock_inventory": (
        37,
        "Virtual Locations/(AR) Responsable Inscripto: Inventory adjustment",
    ),
    "sale_delay": 0.0,
    "tracking": "none",
    "description_picking": False,
    "description_pickingout": False,
    "description_pickingin": False,
    "location_id": False,
    "warehouse_id": False,
    "route_from_categ_ids": [],
    "bom_ids": [],
    "produce_delay": 0.0,
    "life_time": 0,
    "use_time": 0,
    "removal_time": 0,
    "alert_time": 0,
    "taxes_id": [137],
    "supplier_taxes_id": [138],
    "property_account_income_id": False,
    "property_account_expense_id": False,
    "rating_ids": [],
    "rating_last_value": 0.0,
    "rating_count": 0,
    "rating_avg": 0.0,
    "is_seo_optimized": False,
    "website_meta_title": False,
    "website_meta_description": False,
    "website_meta_keywords": False,
    "website_meta_og_img": False,
    "website_published": False,
    "is_published": False,
    "can_publish": True,
    "rating_last_feedback": False,
    "rating_last_image": False,
    "property_account_creditor_price_difference": False,
    "purchase_method": "receive",
    "purchase_line_warn": "no-message",
    "purchase_line_warn_msg": False,
    "cost_method": "standard",
    "valuation": "manual_periodic",
    "available_in_pos": False,
    "to_weight": False,
    "pos_categ_id": False,
    "purchase_requisition": "rfq",
    "route_ids": [27],
    "service_type": "manual",
    "sale_line_warn": "no-message",
    "sale_line_warn_msg": False,
    "expense_policy": "no",
    "visible_expense_policy": True,
    "visible_qty_configurator": True,
    "invoice_policy": "order",
    "optional_product_ids": [],
    "service_to_purchase": False,
    "website_description": False,
    "alternative_product_ids": [],
    "accessory_product_ids": [],
    "website_size_x": 1,
    "website_size_y": 1,
    "website_style_ids": [],
    "website_sequence": 10065,
    "public_categ_ids": [],
    "product_template_image_ids": [],
    "product_add_mode": "configurator",
    "quotation_only_description": False,
    "quotation_description": "",
    "inventory_availability": "never",
    "available_threshold": 0.0,
    "custom_message": "",
    "arba_code": False,
}

# TAXES
{
    "id": 137,
    "name": "IVA 21%",
    "active": True,
    "company_id": (4, "(AR) Responsable Inscripto"),
    "children_tax_ids": [],
    "sequence": 1,
    "description": "IVA 21%",
    "price_include": True,
    "include_base_amount": False,
    "analytic": False,
    "tax_group_id": (2, "IVA 21%"),
    "hide_tax_exigibility": False,
    "tax_exigibility": "on_invoice",
    "cash_basis_transition_account_id": False,
    "cash_basis_base_account_id": False,
    "invoice_repartition_line_ids": [525, 526],
    "refund_repartition_line_ids": [565, 566],
    "country_id": (10, "Argentina"),
    "type_tax_use": "sale",
    "amount": 21.0,
    "withholding_sequence_id": False,
    "withholding_non_taxable_amount": 0.0,
    "withholding_non_taxable_minimum": 0.0,
    "withholding_amount_type": False,
    "withholding_user_error_message": False,
    "withholding_user_error_domain": "[]",
    "withholding_advances": True,
    "withholding_accumulated_payments": False,
    "withholding_python_compute": "\n# withholdable_base_amount\n# payment: account.payment.group object\n# partner: res.partner object (commercial partner of payment group)\n# withholding_tax: account.tax.withholding object\n\nresult = withholdable_base_amount * 0.10\n        ",
    "withholding_rule_ids": [],
    "jurisdiction_code": False,
    "amount_type": "percent",
    "withholding_type": "none",
    "display_name": "IVA 21%",
    "create_uid": (1, "OdooBot"),
    "create_date": datetime.datetime(2021, 6, 14, 21, 11, 9, 26427),
    "write_uid": (13, "Diego Maylin"),
    "write_date": datetime.datetime(2021, 8, 9, 19, 22, 39, 347776),
    "__last_update": datetime.datetime(2021, 8, 9, 19, 22, 39, 347776),
}


[
    {
        "id": 137,
        "name": False,
        "payment_reference": False,
        "move_name": False,
        "destination_account_id": (513, "1.1.3.01.010 Deudores por ventas"),
        "invoice_ids": [],
        "reconciled_invoice_ids": [],
        "has_invoices": False,
        "reconciled_invoices_count": 0,
        "move_line_ids": [],
        "move_reconciled": True,
        "payment_type": "inbound",
        "payment_method_id": (1, "Manual"),
        "payment_method_code": "manual",
        "partner_type": "customer",
        "payment_date": datetime.date(2022, 2, 12),
        "communication": False,
        "company_id": (4, "(AR) Responsable Inscripto"),
        "hide_payment_method": True,
        "payment_difference": 0.0,
        "payment_difference_handling": "open",
        "writeoff_account_id": False,
        "writeoff_label": "Write-Off",
        "partner_bank_account_id": False,
        "show_partner_bank_account": False,
        "require_partner_bank_account": False,
        "store_id": False,
        "state": "draft",
        "amount": 382.05,
        "partner_id": (132, "Prueba 1"),
        "journal_id": (23, "Ventas Manuales (ARS)"),
        "destination_journal_id": False,
        "currency_id": (19, "ARS"),
        "payment_method_description": "Manual",
        "payment_method_ids": [1],
        "journal_ids": [22, 31, 32, 35, 34, 33, 36, 21],
        "destination_journal_ids": [22, 31, 32, 35, 34, 33, 36, 21],
        "activity_ids": [],
        "activity_state": False,
        "activity_date_deadline": False,
        "activity_exception_decoration": False,
        "activity_exception_icon": False,
        "message_is_follower": False,
        "message_follower_ids": [2293],
        "message_partner_ids": [],
        "message_channel_ids": [],
        "message_ids": [3325],
        "message_unread": False,
        "message_unread_counter": 0,
        "message_needaction": False,
        "message_needaction_counter": 0,
        "message_has_error": False,
        "message_has_error_counter": 0,
        "message_attachment_count": 0,
        "message_main_attachment_id": False,
        "website_message_ids": [],
        "message_has_sms_error": False,
        "payment_transaction_id": False,
        "payment_token_id": False,
        "tax_withholding_id": False,
        "withholding_number": False,
        "withholding_base_amount": 0.0,
        "payment_group_id": (83, "yo le puse esto"),
        "payment_group_company_id": (4, "(AR) Responsable Inscripto"),
        "payment_type_copy": "inbound",
        "signed_amount": 382.05,
        "signed_amount_company_currency": 382.05,
        "amount_company_currency": 382.05,
        "other_currency": False,
        "force_amount_company_currency": 0.0,
        "exchange_rate": 0.0,
        "company_currency_id": (19, "ARS"),
        "account_card_ids": [],
        "card_id": False,
        "instalment_id": False,
        "instalment": 0,
        "card_type": False,
        "magnet_bar": False,
        "card_number": False,
        "tiket_number": False,
        "lot_number": False,
        "fee": 0.0,
        "sale_order_id": False,
        "discount": 0.0,
        "bank_discount": 0.0,
        "discount_amount": 0.0,
        "clearing_date": datetime.date(2022, 2, 12),
        "check_ids": [],
        "check_id": False,
        "check_deposit_type": "detailed",
        "check_name": False,
        "check_number": 0,
        "check_issue_date": datetime.date(2022, 2, 12),
        "check_payment_date": False,
        "checkbook_id": False,
        "check_subtype": False,
        "check_bank_id": False,
        "check_owner_vat": False,
        "check_owner_name": False,
        "check_type": False,
        "checkbook_numerate_on_printing": False,
        "automatic": False,
        "withholding_accumulated_payments": False,
        "withholdable_invoiced_amount": 0.0,
        "withholdable_advanced_amount": 0.0,
        "accumulated_amount": 0.0,
        "total_amount": 382.05,
        "withholding_non_taxable_minimum": 0.0,
        "withholding_non_taxable_amount": 0.0,
        "withholdable_base_amount": 0.0,
        "period_withholding_amount": 0.0,
        "previous_withholding_amount": 0.0,
        "computed_withholding_amount": 0.0,
        "cash_control_session_id": False,
        "config_id": False,
        "statement_ids": [],
        "l10n_ar_partner_vat": "30712079378",
        "activity_user_id": False,
        "activity_type_id": False,
        "activity_summary": False,
        "display_name": "Pago en borrador",
        "create_uid": (1, "OdooBot"),
        "create_date": datetime.datetime(2022, 2, 11, 23, 33, 16, 892130),
        "write_uid": (1, "OdooBot"),
        "write_date": datetime.datetime(2022, 2, 11, 23, 33, 16, 892130),
        "__last_update": datetime.datetime(2022, 2, 11, 23, 33, 16, 892130),
    },
]
{
    "id": 44,
    "name": "(AR) Exento",
    "display_name": "(AR) Exento",
    "date": False,
    "title": False,
    "parent_id": False,
    "parent_name": False,
    "child_ids": [],
    "ref": False,
    "lang": "es_AR",
    "active_lang_count": 1,
    "tz": False,
    "tz_offset": "+0000",
    "same_vat_partner_id": (140, "(AR) Exento (copia)"),
    "bank_ids": [],
    "website": "http://www.exento.com",
    "comment": False,
    "category_id": [],
    "credit_limit": 0.0,
    "active": True,
    "employee": False,
    "function": False,
    "type": "contact",
    "street": "Soyexento 123",
    "street2": False,
    "zip": "2000",
    "city": "Rosario",
    "state_id": (573, "Santa Fe (AR)"),
    "country_id": (10, "Argentina"),
    "partner_latitude": 0.0,
    "partner_longitude": 0.0,
    "email": "info@exento.example.com",
    "email_formatted": '"(AR) Exento" <info@exento.example.com>',
    "phone": "+1 555 123 8069",
    "mobile": False,
    "is_company": False,
    "industry_id": False,
    "company_type": "person",
    "company_id": False,
    "color": 0,
    "user_ids": [],
    "partner_share": True,
    "contact_address": "Soyexento 123\n\nRosario Santa Fe 2000\nArgentina",
    "commercial_partner_id": (44, "(AR) Exento"),
    "commercial_company_name": False,
    "company_name": False,
    "self": (44, "(AR) Exento"),
    "im_status": "im_partner",
    "activity_ids": [],
    "activity_state": False,
    "activity_user_id": False,
    "activity_type_id": False,
    "activity_date_deadline": False,
    "activity_summary": False,
    "activity_exception_decoration": False,
    "activity_exception_icon": False,
    "message_is_follower": False,
    "message_follower_ids": [147],
    "message_partner_ids": [],
    "message_channel_ids": [],
    "message_ids": [160],
    "message_unread": False,
    "message_unread_counter": 0,
    "message_needaction": False,
    "message_needaction_counter": 0,
    "message_has_error": False,
    "message_has_error_counter": 0,
    "message_attachment_count": 0,
    "message_main_attachment_id": False,
    "email_normalized": "info@exento.example.com",
    "is_blacklisted": False,
    "message_bounce": 0,
    "channel_ids": [],
    "user_id": False,
    "signup_token": False,
    "signup_type": False,
    "signup_expiration": False,
    "signup_valid": False,
    "signup_url": False,
    "calendar_last_notif_ack": datetime.datetime(2021, 6, 15, 20, 45, 54),
    "partner_gid": 0,
    "additional_info": False,
    "phone_sanitized": False,
    "phone_blacklisted": False,
    "property_product_pricelist": (1, "Tarifa pública (ARS)"),
    "team_id": False,
    "website_message_ids": [],
    "message_has_sms_error": False,
    "property_stock_customer": (5, "Partner Locations/Customers"),
    "property_stock_supplier": (4, "Partner Locations/Vendors"),
    "picking_warn": "no-message",
    "picking_warn_msg": False,
    "helpdesk_ticket_ids": [],
    "helpdesk_ticket_count": 0,
    "helpdesk_ticket_active_count": 0,
    "helpdesk_ticket_count_string": "0 / 0",
    "website_id": False,
    "is_published": False,
    "can_publish": True,
    "website_url": "#",
    "website_published": False,
    "visitor_ids": [],
    "credit": 0.0,
    "debit": 0.0,
    "debit_limit": 0.0,
    "total_invoiced": 0.0,
    "currency_id": (19, "ARS"),
    "journal_item_count": 0,
    "property_account_payable_id": (609, "2.1.1.01.010 Proveedores"),
    "property_account_receivable_id": (513, "1.1.3.01.010 Deudores por ventas"),
    "property_account_position_id": False,
    "property_payment_term_id": False,
    "property_supplier_payment_term_id": False,
    "ref_company_ids": [2],
    "has_unreconciled_entries": False,
    "last_time_entries_checked": False,
    "invoice_ids": [],
    "bank_account_count": 0,
    "trust": "normal",
    "invoice_warn": "no-message",
    "invoice_warn_msg": False,
    "supplier_rank": 0,
    "customer_rank": 0,
    "sale_contract_count": 0,
    "purchase_contract_count": 0,
    "contract_ids": [],
    "payment_token_ids": [],
    "payment_token_count": 0,
    "property_purchase_currency_id": False,
    "purchase_order_count": 0,
    "supplier_invoice_count": 0,
    "purchase_warn": "no-message",
    "purchase_warn_msg": False,
    "l10n_latam_identification_type_id": (4, "CUIT"),
    "vat": "30999999995",
    "pos_order_count": 0,
    "pos_order_ids": [],
    "barcode": False,
    "sale_order_count": 0,
    "sale_order_ids": [],
    "sale_warn": "no-message",
    "sale_warn_msg": False,
    "invoice_price_method": "historical",
    "l10n_ar_vat": "30999999995",
    "l10n_ar_formatted_vat": "30-99999999-5",
    "l10n_ar_gross_income_number": "1241",
    "l10n_ar_gross_income_type": "multilateral",
    "l10n_ar_afip_responsibility_type_id": (4, "IVA Sujeto Exento"),
    "l10n_ar_special_purchase_document_type_ids": [],
    "last_website_so_id": False,
    "receivable_debt_ids": [],
    "payable_debt_ids": [],
    "debt_balance": 0.0,
    "last_update_census": False,
    "gross_income_jurisdiction_ids": [203],
    "start_date": False,
    "estado_padron": False,
    "imp_ganancias_padron": False,
    "imp_iva_padron": False,
    "integrante_soc_padron": False,
    "monotributo_padron": False,
    "actividad_monotributo_padron": False,
    "empleador_padron": False,
    "actividades_padron": [],
    "impuestos_padron": [],
    "last_update_padron": False,
    "arba_alicuot_ids": [],
    "drei": False,
    "default_regimen_ganancias_id": False,
    "create_uid": (1, "OdooBot"),
    "create_date": datetime.datetime(2021, 6, 14, 21, 11, 9, 26427),
    "write_uid": (2, "Mitchell Admin DEBO"),
    "write_date": datetime.datetime(2022, 2, 9, 14, 20, 51, 72602),
    "__last_update": datetime.datetime(2022, 2, 9, 14, 20, 51, 72602),
}
